### ISSUE TITLE
Perfect scroll is not adjusting to the container content change.

### ISSUE THREAD

**Issue by vamsi-kaja** [imanhodjaev/ember-perfect-scroll#13]
I did not find the option to update the perfect-scrollbar when the content of the container changes.

**Comment by feanor07** [comment]
it seems better to define an action within `perfect-scroll` component to update internal `Ps` component and yield it in template. By this way; the users of the component will have to opportunity to trigger update whenever they need.

**Comment by imanhodjaev** [comment]
Awesome @feanor07 thanks!

**Comment by feanor07** [comment]
providing an action to be yielded seemed to be enabling only a limited usage (because the action yielded should only be available within the block usage of the contextual component); hence I decided to go with creating a mixin and providing relevant `updatePerfectScroll` method within the mixin. So that; injecting the mixin to the relevant construct such as component, controller, or router will be enough to perform an update via calling `this.updatePerfectScroll` directly. In order the mixin to control the perfect-scroll; `lifeCycleEventOccurred` event (triggered after initialization and before destroying of the perfect scroll) of the `perfect-sroll` must be handled by the `lifeCycleEventOccurred` action within the mixin. This means `lifeCycleEventOccurred=(action 'lifeCycleEventOccurred')` declaration is neeed within the template for the update to work. You can see relevant section (PerfectScrollController Mixin) of README for usage example.

**Comment by imanhodjaev** [comment]
Once this feature will be in master I can tag a new verson.
Thanks.

**Comment by feanor07** [comment]
we can close this now.
